//
//Queensaver API
//
//Queensaver API to send in sensor data and retrieve it. It's also used for user management.
//
//The version of the OpenAPI document: 0.0.1
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: models/bbox_bhive.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BboxBhive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of a beehive. Is unique for that user.
	BhiveId string `protobuf:"bytes,140936307,opt,name=bhiveId,proto3" json:"bhiveId,omitempty"`
}

func (x *BboxBhive) Reset() {
	*x = BboxBhive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_bbox_bhive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BboxBhive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BboxBhive) ProtoMessage() {}

func (x *BboxBhive) ProtoReflect() protoreflect.Message {
	mi := &file_models_bbox_bhive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BboxBhive.ProtoReflect.Descriptor instead.
func (*BboxBhive) Descriptor() ([]byte, []int) {
	return file_models_bbox_bhive_proto_rawDescGZIP(), []int{0}
}

func (x *BboxBhive) GetBhiveId() string {
	if x != nil {
		return x.BhiveId
	}
	return ""
}

var File_models_bbox_bhive_proto protoreflect.FileDescriptor

var file_models_bbox_bhive_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62, 0x62, 0x6f, 0x78, 0x5f, 0x62, 0x68,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x22, 0x28, 0x0a, 0x09, 0x42, 0x62, 0x6f, 0x78, 0x42, 0x68, 0x69, 0x76, 0x65, 0x12,
	0x1b, 0x0a, 0x07, 0x62, 0x68, 0x69, 0x76, 0x65, 0x49, 0x64, 0x18, 0xf3, 0x88, 0x9a, 0x43, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x68, 0x69, 0x76, 0x65, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_bbox_bhive_proto_rawDescOnce sync.Once
	file_models_bbox_bhive_proto_rawDescData = file_models_bbox_bhive_proto_rawDesc
)

func file_models_bbox_bhive_proto_rawDescGZIP() []byte {
	file_models_bbox_bhive_proto_rawDescOnce.Do(func() {
		file_models_bbox_bhive_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_bbox_bhive_proto_rawDescData)
	})
	return file_models_bbox_bhive_proto_rawDescData
}

var file_models_bbox_bhive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_bbox_bhive_proto_goTypes = []interface{}{
	(*BboxBhive)(nil), // 0: openapi.BboxBhive
}
var file_models_bbox_bhive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_bbox_bhive_proto_init() }
func file_models_bbox_bhive_proto_init() {
	if File_models_bbox_bhive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_bbox_bhive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BboxBhive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_bbox_bhive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_bbox_bhive_proto_goTypes,
		DependencyIndexes: file_models_bbox_bhive_proto_depIdxs,
		MessageInfos:      file_models_bbox_bhive_proto_msgTypes,
	}.Build()
	File_models_bbox_bhive_proto = out.File
	file_models_bbox_bhive_proto_rawDesc = nil
	file_models_bbox_bhive_proto_goTypes = nil
	file_models_bbox_bhive_proto_depIdxs = nil
}
