//
//Queensaver API
//
//Queensaver API to send in sensor data and retrieve it. It's also used for user management.
//
//The version of the OpenAPI document: 0.0.1
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: models/get_temperature.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTemperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the internal user id of the authenticated user. Will be set internally in the cloud system and does not have an effect if set via the API call as it will be overridden. Don't set this value.
	UserId       float32        `protobuf:"fixed32,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Temperatures []*Temperature `protobuf:"bytes,2,rep,name=temperatures,proto3" json:"temperatures,omitempty"`
	// error
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpReponseCode int32 `protobuf:"varint,4,opt,name=httpReponseCode,proto3" json:"httpReponseCode,omitempty"`
}

func (x *GetTemperature) Reset() {
	*x = GetTemperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_get_temperature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemperature) ProtoMessage() {}

func (x *GetTemperature) ProtoReflect() protoreflect.Message {
	mi := &file_models_get_temperature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemperature.ProtoReflect.Descriptor instead.
func (*GetTemperature) Descriptor() ([]byte, []int) {
	return file_models_get_temperature_proto_rawDescGZIP(), []int{0}
}

func (x *GetTemperature) GetUserId() float32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTemperature) GetTemperatures() []*Temperature {
	if x != nil {
		return x.Temperatures
	}
	return nil
}

func (x *GetTemperature) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTemperature) GetHttpReponseCode() int32 {
	if x != nil {
		return x.HttpReponseCode
	}
	return 0
}

var File_models_get_temperature_proto protoreflect.FileDescriptor

var file_models_get_temperature_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x1a, 0x18, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0c,
	0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x0f,
	0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_get_temperature_proto_rawDescOnce sync.Once
	file_models_get_temperature_proto_rawDescData = file_models_get_temperature_proto_rawDesc
)

func file_models_get_temperature_proto_rawDescGZIP() []byte {
	file_models_get_temperature_proto_rawDescOnce.Do(func() {
		file_models_get_temperature_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_get_temperature_proto_rawDescData)
	})
	return file_models_get_temperature_proto_rawDescData
}

var file_models_get_temperature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_get_temperature_proto_goTypes = []interface{}{
	(*GetTemperature)(nil), // 0: openapi.GetTemperature
	(*Temperature)(nil),    // 1: openapi.Temperature
}
var file_models_get_temperature_proto_depIdxs = []int32{
	1, // 0: openapi.GetTemperature.temperatures:type_name -> openapi.Temperature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_get_temperature_proto_init() }
func file_models_get_temperature_proto_init() {
	if File_models_get_temperature_proto != nil {
		return
	}
	file_models_temperature_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_get_temperature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_get_temperature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_get_temperature_proto_goTypes,
		DependencyIndexes: file_models_get_temperature_proto_depIdxs,
		MessageInfos:      file_models_get_temperature_proto_msgTypes,
	}.Build()
	File_models_get_temperature_proto = out.File
	file_models_get_temperature_proto_rawDesc = nil
	file_models_get_temperature_proto_goTypes = nil
	file_models_get_temperature_proto_depIdxs = nil
}
