/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Bhive struct {

	// The ID of a beehive. Is unique for that user.
	BhiveId string `json:"bhive_id,omitempty"`
}

// AssertBhiveRequired checks if the required fields are not zero-ed
func AssertBhiveRequired(obj Bhive) error {
	return nil
}

// AssertRecurseBhiveRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Bhive (e.g. [][]Bhive), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBhiveRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBhive, ok := obj.(Bhive)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBhiveRequired(aBhive)
	})
}
