/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VarroaScanMetadata struct {

	// class
	Class string `json:"class,omitempty"`
}

// AssertVarroaScanMetadataRequired checks if the required fields are not zero-ed
func AssertVarroaScanMetadataRequired(obj VarroaScanMetadata) error {
	return nil
}

// AssertRecurseVarroaScanMetadataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VarroaScanMetadata (e.g. [][]VarroaScanMetadata), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseVarroaScanMetadataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVarroaScanMetadata, ok := obj.(VarroaScanMetadata)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertVarroaScanMetadataRequired(aVarroaScanMetadata)
	})
}
