/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BboxBhive struct {

	// The ID of a beehive. Is unique for that user.
	BhiveId string `json:"bhiveId,omitempty"`
}

// AssertBboxBhiveRequired checks if the required fields are not zero-ed
func AssertBboxBhiveRequired(obj BboxBhive) error {
	return nil
}

// AssertRecurseBboxBhiveRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BboxBhive (e.g. [][]BboxBhive), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBboxBhiveRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBboxBhive, ok := obj.(BboxBhive)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBboxBhiveRequired(aBboxBhive)
	})
}
